# Generated by Django 4.2.6 on 2024-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('comments', models.TextField(null=True)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CommentsModel',
            },
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('like', models.IntegerField(null=True)),
                ('dislike', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'LikesModel',
            },
        ),
        migrations.CreateModel(
            name='UploadBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tag', models.EmailField(max_length=254, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('blog_pic', models.FileField(upload_to='static\\blog_pic')),
                ('post_type', models.CharField(max_length=50, null=True)),
                ('time_field', models.DateTimeField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('tagby', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'UploadBlogModel',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('profile_picture', models.FileField(upload_to='static\\profile_pictures')),
                ('profilename', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
